### ISSUE TITLE
Purchasing screen

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#103]
When you start a new vineyard planning, it will eventually takes you to a purchasing page; however, there is no link to get out from the page.

![image](https://user-images.githubusercontent.com/23525183/54477827-dd729b00-47e1-11e9-8385-6c730897cbfe.png)

We do not need a new link on the page, but we probably should say "Click home to go back to the dashboard" or something like that line.

**Comment by rburghol** [comment]
The main menu is the place to do this -- it is pretty much the same for all pages (though a handful DO have a return button of some sort.

![image](https://user-images.githubusercontent.com/4571170/54989262-89f50f80-4f8e-11e9-8736-24cf8ad072b6.png)
