### ISSUE TITLE
Missing FRAC code in the current material list

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#106]
Some products are missing FRAC code, when it is displayed in the current material list.

![image](https://user-images.githubusercontent.com/23525183/54478100-1e1fe380-47e5-11e9-9961-ee3534e09920.png)

**Comment by rburghol** [comment]
These will need to be edited by hand -- at least those that I have verified simply lacked a FRAC code.  Some are duplicates and need to be deleted (multiple entries were imported).
