### ISSUE TITLE
Block appears twice?

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#109]
When you are trying to add a block to an existing vineyard, it won't reflect the cultivar. You can add to the list of blocks once you create one, but you cannot edit or delete the one without the cultivar information. (add/edit all blocks will ADD a new block, when you enter cultivar information) Once you create two blocks (one with and another without cultivar info), deleting one will delete both.

![image](https://user-images.githubusercontent.com/23525183/54478283-cbdfc200-47e6-11e9-9beb-ec270c9e50ed.png)

![image](https://user-images.githubusercontent.com/23525183/54478256-815e4580-47e6-11e9-93be-808fb62bb1c4.png)

**Comment by rburghol** [comment]
This was a bug with the add block work flow.  I have removed that work flow, and now, the only workflow is the "Edit All Blocks" work flow.
