### ISSUE TITLE
Display of canceled events

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#164]
It would be nice to be able to differentiate the canceled events. Currently, both planned and completed and planned and canceled events are shown the same manner.

![image](https://user-images.githubusercontent.com/23525183/71480666-4bfc7480-27c8-11ea-9ba1-94612625008d.png)

Maybe showing in gray? Anything to show visually is good. Thanks!!!

**Comment by rburghol** [comment]
This is a great idea.  I think we can maybe even use the ~~strike-through~~ notation for this.

**Comment by nita24** [comment]
Strikethrough sounds good.

**Comment by rburghol** [comment]
Fixed.

**Comment by nita24** [comment]
Looking good. Thank you!

Mizuho (from a mobile device.)
