### ISSUE TITLE
Units in Plan are not shown correctly

### ISSUE THREAD

**Issue by mikako534** [rburghol/om_agman#175]
Hello Robert @rburghol ,
Thank you for adding me to this working group.

Sometimes the units of pestcides are shown incorrectly in the Plan page.
In this case, while "Mettle 125 ME @ 3floz" looks good (blue in pictures),
"Lime Sulfur Solution @ 10" and "Champ Formula 2 Flowable @ 2 floz" (red ones)
have incorrect units; it should be 
"Lime Sulfur Solution @ 10 gal(s)" and "Champ Formula 2 Flowable @ 2 pint(s)",
according to the event pages below.

"Plan":
[http://www.grapeipm.org/d.live/ipm-facility-sprayplan/1541/1641](http://www.grapeipm.org/d.live/ipm-facility-sprayplan/1541/1641)
![image](https://user-images.githubusercontent.com/61061788/74659820-02465f80-5163-11ea-810a-530c421404ee.png)
![image](https://user-images.githubusercontent.com/61061788/74660745-be545a00-5164-11ea-8c8c-fae7e9c2b70c.png)

"Add Event" or Edit event:

![image](https://user-images.githubusercontent.com/61061788/74660998-26a33b80-5165-11ea-9b9e-6c3c68499ae8.png)

![image](https://user-images.githubusercontent.com/61061788/74660903-fe1b4180-5164-11ea-8be0-2b058011c578.png)

I am not sure when it occurs.
I would be appreciate if you could find a way to fix it.

Thank you, 
Mikako @mikako534

**Comment by mikako534** [comment]
I am sorry for bothering you, but I could fix it by modifing some information on the registration list.
Thank you.
Mikako

**Comment by rburghol** [comment]
Thanks for sorting this out Mikako!
