### ISSUE TITLE
Mispelling

### ISSUE THREAD

**Issue by AmandaBly9** [rburghol/om_agman#245]
Once you open the list of diseases under chemicals, "Macrophoma" is spelled incorrectly. 

Also, as we both know, I haven't been using this platform so there's a chance I'm not using it correctly...

**Comment by rburghol** [comment]
This is absolutely the right way to use this :) -- I just edited that now -- if you can confirm that I fixed it that would be snazzy.

**Comment by AmandaBly9** [comment]
I checked, spelling corrected !

Thanks for quick feedback.
-A
