### ISSUE TITLE
Chemical Search Page Heading

### ISSUE THREAD

**Issue by AmandaBly9** [rburghol/om_agman#247]
What if the title to the chemical search page was something more 'user friendly.' http://www.grapeipm.org/d.live/dha-list-prs/149

'Registered Chemicals' 

'Search Registered Chemicals' 

'Chemical Formulations List' 

'Chemical Formulations Database' 

List of Chemical Formulations

**Registered Chemical Formulations

Search Registered Chemical Formulations**  Last two are my favorite. 

(Incoming -- more feedback on this chemical search/filter page)

**Comment by AmandaBly9** [comment]
[Screenshot 1_4.2.2021.docx](https://github.com/rburghol/om_agman/files/6249964/Screenshot.1_4.2.2021.docx)

**Comment by hdaniel7** [comment]
The agrichemical search page title has been updated to 'Search Registered Chemical Formulations'
