### ISSUE TITLE
PMG - Yes or No

### ISSUE THREAD

**Issue by AmandaBly9** [rburghol/om_agman#250]
Since there are only two options for filtering PMG information  (Yes or No) could this also be a drop down. 

Also, perhaps the heading could be "Listed in PMG" without punctuation and then the associated drop down list.

**Comment by AmandaBly9** [comment]
[Screenshot 1_4.2.2021.docx](https://github.com/rburghol/om_agman/files/6250000/Screenshot.1_4.2.2021.docx)

**Comment by rburghol** [comment]
Yup - will do!

**Comment by rburghol** [comment]
This will be included in the new chem search interface!

**Comment by rburghol** [comment]
See #262
