### ISSUE TITLE
Title for the trend figure

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#269]
It looks like the subtitle is working, so, how about not showing the main title? or use what we have for the subtitle for the main title? Or a generic title like "Trendline"?

![image](https://user-images.githubusercontent.com/23525183/115921024-f631ee00-a448-11eb-9ab5-b7f1b3ba44e0.png)

Ex: http://www.grapeipm.org/d.live/ipm-event-trends/120458417/147/agman_fruit_chem

**Comment by hdaniel7** [comment]
Title has been changed to "Trend Analysis"
