### ISSUE TITLE
Test highlight years

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#305]
![image](https://user-images.githubusercontent.com/23525183/140526773-08fd9897-3a20-4081-9ab7-3e7d4de5626b.png)

**Comment by nita24** [comment]
Scribble dissapeard-- please make years more visible.

**Comment by rburghol** [comment]
proposed fix added 12/2021. Please re-open if this doesn't achieve the goal.

![518AA8BD-9BE5-44E8-9E3A-C4ECC6C001F7](https://user-images.githubusercontent.com/4571170/151714514-0bc78645-caf0-4e9e-95a2-dfb930af1029.jpeg)

**Comment by nita24** [comment]
Looking good to me. Thank you!
