### ISSUE TITLE
iOS issue?

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#309]
![image](https://user-images.githubusercontent.com/23525183/141697562-30b4d7fd-5b96-4490-aefd-03e3f50aca4c.jpeg)
I am not sure I am the only one, but I have a difficulty logging in with the iOS device (iPad). It seems like I have to reload after I enter credentials. It used to work, but now I get an error message.

**Comment by nita24** [comment]
![image](https://user-images.githubusercontent.com/23525183/141697700-4464a7c7-433e-4b46-81cd-70c824bc29aa.jpeg)

**Comment by rburghol** [comment]
Good catch! This should be fixed (affected users with multiple vineyards)
