### ISSUE TITLE
Location edit function

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#31]
When you edit your location after setting it up initially, it saves and I can see the new information saved. However, after the save, it brings me back to the location information page "Locations" which does not reflect the change.

(Once again, fix it when you feel better. This one is not high in the priority anyway)

**Comment by rburghol** [comment]
This appears to be sorted out.  I have verified that we can create new blocks, update their location using the map interface (point only -- I disabled polygon editing for the time being -- it's pretty hard to do well).  Going to do a how-to video on location adding/editing next week!
