### ISSUE TITLE
Location of the inventory

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#334]
Hi Robert,
Is it possible to move the inventory function from Settings to Report?
I think people will consider it as a report, rather than the setting for the vineyard.

https://www.awesomescreenshot.com/video/15561507?key=6095a221e1846cfa2f3a4a9076b346a3

Thanks!
Mizuho

**Comment by rburghol** [comment]
Yeah, this should be very straight-forward.  Gonna try to fix it first!

**Comment by rburghol** [comment]
I moved the purchasing report to the "Reports" area.  I think that makes a ton of sense!
Now, just go to "Reports" and select "Estimate Spray Material Purchasing" from that menu.
