### ISSUE TITLE
Disease models...

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#36]
**This is more like a reminder.** None of disease models are running correctly. For example, Bot model showed a high risk yesterday morning (before the rain), and all models are showing no risk today after nearly 24 hours of rain.... We really need to work on this one before we release it.

**Comment by rburghol** [comment]
Definitely.  As a note, I have modfied the interface so that the disease risk models show up for people with IPM Admin role (you and me), but hidden for all others. So we can develop and use as we see fit without worry of confusing folks who are beta testing.

**Comment by rburghol** [comment]
Did some work on these today — they were there as a placeholder and not updating (as you noticed!) — not sure I like their output, but they are at least representing the python models output.

**Comment by rburghol** [comment]
Disease risks functioning now — enhancements will be planned in a separate thread.
