### ISSUE TITLE
New User experiences: Part 1

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#37]
1) Email: It tends to go to the spam email. VT email address must have been on the blacklist (hahaha) We should probably state something like this on the top page. "Once you submit your request, you should receive an automated email from our system administrator within 30 min. Please check your spam folder. Then you will receive a link to activate your account from us within 24 hours."

**Comment by rburghol** [comment]
Finished setting up grapeipm.org emails this morning, separated the fungicide adding comment to a new issue so we can track these individually. Hopefully the emails will reduce spam filter trouble!
