### ISSUE TITLE
New user experience, Part 2

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#38]
3) I have clicked my cultivar link and find the list of materials... But once again, we should have a link to lead users to it.

4) Please switch the location of "planning" and "add spray".  Otherwise, people might think that adding one by one is the way to go.

5) I planned my spray. There is still a comma in front of some (but not) all sprays.  Strange...

![image](https://user-images.githubusercontent.com/23525183/39874258-4f107ffc-543b-11e8-85f9-7e682ed79946.png)

I think we need a link for users to go back to the dashboard...

![image](https://user-images.githubusercontent.com/23525183/39874343-79fe4c4e-543b-11e8-85e0-011becf692cb.png)

6) Or there should be an instruction at the top of the planning page saying that "Once you entered your materials for the season, click 'home' to go back to your dashboard."

7) Next is to link the weather station: I think this is where we need to spend more time this year. Weather Underground link function needs to be in place. The NEWA probably takes a lot longer time to introduce the API...

**Comment by rburghol** [comment]
3. Plan access added to main menu
4. “Plan” is default when coming eventd are empty.
5. Menu system takes care of navigation now — comma bug still be sorted out (moved to separate issue).
6. Handled by new menu system.
7. Separate issue.
