### ISSUE TITLE
New user experience, Part 3

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#39]
Here's the dashboard.
![image](https://user-images.githubusercontent.com/23525183/39874578-2f43e8a2-543c-11e8-91aa-55c995b970f1.png)

- Is it possible to add "Past planned spray" at the end so that people can access to it to mark as done?

And if I click on the upcoming spray, I see these at the end.
I don't see a way to mark this spray as done, when the time comes.

![image](https://user-images.githubusercontent.com/23525183/39874685-7f03d0b4-543c-11e8-8f4c-824e6699ad1f.png)

**Comment by rburghol** [comment]
Completed button added
Past sprays now shown (full year)
