### ISSUE TITLE
Action page

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#4]
![image](https://user-images.githubusercontent.com/23525183/34426563-546dda62-ec7b-11e7-80dc-087cdf066fce.png)

"Action" mode:
I will play around to see if I can mimic we are already in a season, but what I am thinking is this.
1) We need to have a better wording so that people understand that the link below the planned program is to store their activity / change your plan. 
2) Create a window (frame) below the dashboard where my comments (in the future, comments from Doug as well) will appear as the season progresses.
3) Diseases to be covered by the spray (maybe all we need is to show next planned application? )

**Comment by rburghol** [comment]
I am thinking about a color-coded system to show coverage that is similar to the risk coding.  So, green if you are excellent, etc... maybe use squares instead of circles to show that we are talking about coverage not risk.  This would be fairly easy to implement and also very mobile layout friendly.

**Comment by nita24** [comment]
#3) Sounds good how about having them stacked. Top row for the risks and the second row for the coverage?

**Comment by rburghol** [comment]
Here is the more detailed Actions screen.  I think the goal here should be to have all information needed to do the spray right here, then they can go to edit the event if they need to make changes.  I replaced the long "Go to ..." with a link on the event title and the "pencil" edit icon:
![image](https://user-images.githubusercontent.com/4571170/34439454-200eb4ca-ec7c-11e7-9a96-7ea527c287b0.png)

**Comment by rburghol** [comment]
The water volume and chem amounts are now included in the iCal export so a user in the field need only open their phone calendar and they have all needed details to complete the spray.

![image](https://user-images.githubusercontent.com/4571170/34440412-003c23f6-ec83-11e7-9b9e-2fadf30e803c.png)

**Comment by rburghol** [comment]
#10

**Comment by nita24** [comment]
Having iCal maybe the easiest way to go. Once we have this in place, I think it will be much easier to sell. Good thinking!
