### ISSUE TITLE
Adding a new disease (or insect pest) to the target list

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#79]
If there is a function to add a new disease or insect pest to the pesticide target list, that would be great.

**Comment by rburghol** [comment]
Per conversation -- this isn't quite there, but all the previously added diseases are in place -- like ripe rot -- the widget was only showing 25 records, but we had over 30.  I'm going to close this issue and if we need to have custom edit form for the pesticides we will add it there.
