### ISSUE TITLE
PHI and REI not showing on 

### ISSUE THREAD

**Issue by nita24** [rburghol/om_agman#84]
REI and PHI for newly added materials are not showing up on the "Select Material" screen. It does shown on the list permits screen, so, data should be there...

![image](https://user-images.githubusercontent.com/23525183/52900403-3b9c6600-31c3-11e9-8bc2-076a547f566b.png)

![image](https://user-images.githubusercontent.com/23525183/52900436-b49bbd80-31c3-11e9-8cbe-eaa18dc3d9e2.png)

**Comment by rburghol** [comment]
Will get on this!

**Comment by rburghol** [comment]
All fixed up!
